[![replay-verify](https://github.com/pacan4ikx/aptos-core-aptos-cli-v1.0/actions/workflows/replay-verify.yaml/badge.svg?event=project)](https://github.com/pacan4ikx/aptos-core-aptos-cli-v1.0/actions/workflows/replay-verify.yaml)            - name: First interaction
  uses: actions/first-interaction@v1.3.0
  with:
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # Comment to post on an individual's first issue
    issue-message: # optional
    # Comment to post on an individual's first pull request
    pr-message: # optional
          
